// Generated by My Favourite Pokemon
window.FAVOURITE_POKEMON_DATA = [
  {
    "id": "80f746dc7e9fd19c53d2381e",
    "title": "Type Shinies",
    "text": "Normal | zoroark hisui-s\nFire | ponyta-s\nWater | golisopod-s\nGrass | eldegoss-s\nElectric | luxray-s\nIce | vanillite-s\nFighting | falinks-s\nPoison | skorupi-s\nGround | sandygast-s\nFlying | rookidee-s\nPsychic | ralts-s\nBug | wurmple-s\nRock | relicanth-s\nGhost | sinistea-s\nDragon | hydrapple-s\nDark | nickit-s\nSteel | honedge-s\nFairy | florges-s"
  },
  {
    "id": "80f746dc7e9fd19c53d2381e",
    "title": "Group Shinies",
    "text": "Kanto Starter | ivysaur-s\nJohto Starter | cyndaquil-s\nHoenn Starter | mudkip-s\nSinnoh Starter | empoleon-s\nUnova Starter | servine-s\nKalos Starter | braixen-s\nAlola Starter | dartrix-s\nGalar Starter | rillaboom-s\nHisui Starter | samurott hisui-s\nPaldea Starter | skeledirge-s\nLegendary | giratina-altered-s\nMythical | meloetta pirouette-s\nEeveelution | Vaporeon-s\nFossil | Kabuto-s\nLegendary Bird | Articuno-s\nLegendary Beast | raikou-s\nRegi | regigigas-s\nEon | Latias-s\nSword of justice | virizion-s\nTapu | Tapu koko-s\nUltra Beast | naganadel-s\nAlolan form | rattata alola-s\nGalarian form | voltorb hisui-s\nHisuian form | ponyta galar-s\nPsuedo-legendary | Dragapult-s\nPast Paradox | slither wing-s\nFuture Paradox | iron valiant-s\nTreasure of Ruin | chi-yu-s\n"
  },
  {
    "id": "555fadbfa6335819c5393d97b",
    "title": "Starter 1st Evo.",
    "text": "Gen 1 | Bulbasaur\nGen 2 | Cyndaquil\nGen 3 | Mudkip\nGen 4 | Turtwig\nGen 5 | Oshawott\nGen 6 | Fennekin\nGen 7 | Rowlet\nGen 8 | Scorbunny\nGen 9 | Fuecoco"
  },
  {
    "id": "369dbf0757ce519c5393d97b",
    "title": "Starter 2nd Evo.",
    "text": "Gen 1 | Wartortle\nGen 2 | Bayleef\nGen 3 | Marshtomp\nGen 4 | Monferno\nGen 5 | Dewott\nGen 6 | Braixen\nGen 7 | Dartrix\nGen 8 | Thwackey\nGen 9 | Floragato"
  },
  {
    "id": "e0bd908722ac219c53b887af",
    "title": "Starter 3rd Evo.",
    "text": "Gen 1 | Blastoise\nGen 2 | Typhlosion\nGen 3 | Swampert\nGen 4 | Torterra\nGen 5 | Emboar\nGen 6 | Delphox\nGen 7 | Decidueye\nGen 8 | Inteleon\nGen 9 | Skeledirge"
  },
  {
    "id": "2120e6a7a55dd819c53b88ad3",
    "title": "Kanto",
    "text": "Normal | Eevee\nFire | Vulpix\nWater | Seadra\nGrass | Ivysaur\nElectric | Pikachu\nIce | Cloyster\nFighting | Mankey\nPoison | Nidoran-m\nGround | Sandslash\nFlying | Pidgeotto\nPsychic | Hypno\nBug | Venomoth\nRock | Rhyhorn\nGhost | Haunter\nDragon | Dragonair\nDark | ???\nSteel | Magnemite\nFairy | Clefairy"
  },
  {
    "id": "5c671847f83cb819c53b88dd5",
    "title": "Johto",
    "text": "Normal | Teddiursa\nFire | Houndour\nWater | Azumarill\nGrass | Bellossom\nElectric | Mareep\nIce | Piloswine\nFighting | Heracross\nPoison | Crobat\nGround | Phanpy\nFlying | Gligar\nPsychic | Girafarig\nBug | Spinarak\nRock | Sudowoodo\nGhost | Misdreavus\nDragon | Kingdra\nDark | Umbreon\nSteel | Scizor\nFairy | Togetic"
  },
  {
    "id": "9a16fda573cbf19c53d22370",
    "title": "Hoenn",
    "text": "Normal | Delcatty\nFire | Torkoal\nWater | Feebas\nGrass | Cacnea\nElectric | Plusle\nIce | Walrein\nFighting | Breloom\nPoison | Gulpin\nGround | Flygon\nFlying | Masquerain\nPsychic | Chimecho\nBug | Shedinja\nRock | Armaldo\nGhost | Duskull\nDragon | Bagon\nDark | Crawdaunt\nSteel | Beldum\nFairy | Gardevoir"
  },
  {
    "id": "cd8d90ed9239a819c53d231df",
    "title": "Sinnoh/Hisui",
    "text": "Normal | wyrdeer\nFire | Magmortar\nWater | Buizel\nGrass | Leafeon\nElectric | Luxray\nIce | Froslass\nFighting | Croagunk\nPoison | Roserade\nGround | Gliscor\nFlying | Mantyke\nPsychic | Chingling\nBug | Mothim\nRock | kleavor\nGhost | Zorua-hisui\nDragon | Garchomp\nDark | Weavile\nSteel | Lucario\nFairy | Togekiss"
  },
  {
    "id": "8e666d55dfef119c53d232f2",
    "title": "Unova",
    "text": "Normal | Cinccino\nFire | Litwick\nWater | carracosta\nGrass | Simisage\nElectric | Galvantula\nIce | Vanillite\nFighting | Scrafty\nPoison | Foongus\nGround | Golett\nFlying | Rufflet\nPsychic | Beheeyem\nBug | Dwebble\nRock | Roggenrola\nGhost | Yamask\nDragon | Fraxure\nDark | Zweilous\nSteel | Ferrothorn\nFairy | Whimsicott"
  },
  {
    "id": "968ad64b634a819c53d2345c",
    "title": "Kalos",
    "text": "Normal | furfrou\nFire | fletchinder\nWater | Clawitzer\nGrass | pumpkaboo\nElectric | dedenne\nIce | bergmite\nFighting | Hawlucha\nPoison | Dragalge\nGround | Diggersby\nFlying | noibat\nPsychic | Meowstic-male\nBug | Spewpa\nRock | carbink\nGhost | Phantump\nDragon | Sliggoo\nDark | Inkay\nSteel | Honedge\nFairy | Sylveon"
  },
  {
    "id": "1c6ab7e763904819c53d23598",
    "title": "Alola",
    "text": "Normal | yungoos\nFire | marowak-alola\nWater | golisopod\nGrass | steenee\nElectric | golem-alola\nIce | vulpix-alola\nFighting | stufful\nPoison | salandit\nGround | sandygast\nFlying | pikipek\nPsychic | morelull\nBug | dewpider\nRock | rockruff\nGhost | dhelmise\nDragon | drampa\nDark | meowth-alola\nSteel | sandshrew-alola\nFairy | mimikyu"
  },
  {
    "id": "2c229723660eb19c53d236a4",
    "title": "Galar",
    "text": "Normal | Wooloo\nFire | carkol\nWater | drednaw\nGrass | Eldegoss\nElectric | toxtricity-amped\nIce | darumaka-galar\nFighting | clobbopus\nPoison | weezing-galar\nGround | silicobra\nFlying | rookidee\nPsychic | ponyta-galar\nBug | centiskorch\nRock | stonjourner\nGhost | Sinistea\nDragon | Applin\nDark | Nickit\nSteel | meowth-galar\nFairy | Alcremie"
  },
  {
    "id": "80f746dc7e9fd19c53d2381e",
    "title": "Paldea",
    "text": "Normal | lechonk\nFire | armarouge\nWater | finizen\nGrass | dolliv\nElectric | pawmo\nIce | cetitan\nFighting | annihilape\nPoison | wooper-paldea\nGround | toedscruel\nFlying | wattrel\nPsychic | farigiraf\nBug | tarountula\nRock | naclstack\nGhost | poltchageist\nDragon | hydrapple\nDark | mabosstiff\nSteel | varoom\nFairy | tinkaton"
  },
  {
    "id": "80f746dc7e9fd19c53d2381e",
    "title": "OVERALL FAVOURITES",
    "text": "Normal | Wyrdeer\nFire | litwick\nWater | golisopod\nGrass | eldegoss\nElectric | galvantula\nIce | piloswine\nFighting | breloom\nPoison | nidoran m\nGround | sandslash\nFlying | pidgeotto\nPsychic | morelull\nBug | spewpa\nRock | rockruff\nGhost | phantump\nDragon | hydrapple\nDark | crawdaunt\nSteel | honedge\nFairy | tinkaton"
  },
  {
    "id": "688be4c457314819c53e534e6",
    "title": "Pokemon Groups",
    "text": "Overall Legendary | Koraidon\nOverall Mythical | Shaymin land\nHitmons | hitmonchan\nFossil Pokemon | Anorith\nEeveelution | Leafeon\nPikaclones | plusle\nElemental Monkeys | Simisage\nArtificial Pokemon | Trubbish\nObject Pokemon | vanillite\nBaby pokemon | Munchlax\nExtraterrestrial | cosmog\npsuedo-legendary | Dragapult\n"
  },
  {
    "id": "bff6edaf1bd0819c54350b6a",
    "title": "Species Forms",
    "text": "castform | castform rainy\nRotom | rotom wash\nOricorio | oricorio baile\nlycanroc | lycanroc midday\nminior | minior orange\ntoxtricity | toxtricity amped\ntauros | tauros blaze\nsquawkabilly | squawkabilly blue\ntatsugiri | tatsugiri curly\nbasculin | basculin red striped\n"
  },
  {
    "id": "bff6edaf1bd0819c54350b6a",
    "title": "Regional Variants",
    "text": "Rattata | rattata alola\nraticate | raticate\nraichu | raichu alola\nsandshrew | sandshrew alola\nshandslash | sandslash\nvulpix | vulpix alola\nninetales | ninetales\ndiglett | diglett\ndugtrio | dugtrio\nmeowth | meowth galar\npersian | persian\ngrowlithe | growlithe\narcanine | arcanine\ngeodude | geodude alola\ngraveler | graveler alola\ngolem | golem alola\nponyta | ponyta galar\nrapidash | rapidash\nslowpoke | slowpoke\nslowbro | slowbro galar\nslowking | slowking\nfarfetchd | farfetchd\ngrimer | grimer alola\nmuk | muk\nvoltorb | voltorb hisui\nelectrode | electrode\nexeggutor | exeggutor alola\nmarowak | marowak alola\ntauros | tauros blaze\narticuno | articuno galar\nzapdos | zapdos galar\nmoltres | moltres galar\ntyphlosion | typhlosion hisui\nwooper | wooper\nqwilfish | qwilfish hisui\nsneasel | sneasel\ncorsola | corsola\nzigzagoon | zigzagoon\nlinoone | linoone\nsamurott | samurott\nlilligant | lilligant\ndarumaka | darumaka galar\ndarmanitan | darmanitan standard\ndarmanitan zen | darmanitan galar zen\nyamask | yamask galar\nzorua | zorua hisui\nzoroark | zoroark hisui\nstunfisk | stunfisk\nsliggoo | sliggoo\ngoodra | goodra\navalugg | avalugg hisui\ndecidueye | decidueye"
  },
  {
    "id": "bff6edaf1bd0819c54350b6a",
    "title": "Convergent Species",
    "text": "Tentacool/Toedscool | Tentacool\nTentacruel/Toedscruel | Tentacruel\nDiglett/Wiglett | Wiglett\nDugtrio/Wugtrio | Wugtrio\nSinistea/Poltchageist | Poltchageist\nPolteageist/Sinistcha | Polteageist"
  },
  {
    "id": "bff6edaf1bd0819c54350b6a",
    "title": "Gimmick Form Groups",
    "text": "Mega Evolution | golurk mega\nMega Evolution Starter | chesnaught mega\nGigantamax | snorlax gmax\nGigantamax Starter | Blastoise gmax\nPast Paradox | Slither Wing\nFuture Paradox | Iron Valiant\n"
  },
  {
    "id": "cf5fa339d77cf819c5481dee2",
    "title": "Kanto Legends",
    "text": "Legendary Bird | Articuno\n★ Legendary Bird | Articuno-s\nMew / Mewtwo | Mewtwo\n★ Mew / Mewtwo | Mewtwo-s"
  },
  {
    "id": "c8ac65b58893b819c548235bd",
    "title": "Johto Legends",
    "text": "Legendary Beast | Raikou\n★ Legendary Beast | Raikou-s\nLegendary Giants| Regirock\n★ Legendary Giants| Regigigas-s\nTower Duo | Lugia\n★ Tower Duo | Lugia-s"
  },
  {
    "id": "e488c256380bd19c54829d5d",
    "title": "Hoenn Legends",
    "text": "Eon Duo | Latias\n★ Eon Duo | Latias-s\nDeoxys | Deoxys attack\nWeather Trio | Rayquaza\n★ Weather Trio | Rayquaza-s\nWeather Trio Primal | Kyogre-primal\n★ Weather Trio Primal | kyogre-primal-s\n"
  },
  {
    "id": "dfec4c87e03ac819c54835f17",
    "title": "Sinnoh Legends",
    "text": "Lake Trio | Uxie\n★ Lake Trio | Azelf-s\nLuna Duo | Cresselia\n★ Luna Duo | Cresselia-s\nPokemon of Myth | Palkia\n★ Pokemon of Myth | Palkia-s\nOrigin Forms | Giratina origin\n★ Origin Forms | giratina origin-s\nShaymin | shaymin land\n★ Shaymin | shaymin land-s\n"
  },
  {
    "id": "59ca4ebcae7fd819c5483d849",
    "title": "Unova Legends",
    "text": "Forces of Nature | tornadus incarnate\nForces of Nature Therian | landorus therian\nTao Trio | zekrom\nZyurem | kyurem black\n"
  },
  {
    "id": "8efea319c9403819c54844ef3",
    "title": "Kalos Legends",
    "text": "Swords of Justice | terrakion\nMeloetta | meloetta pirouette\nHoopa | Hoopa\nAura Trio | Xerneas\nZygarde Form | zygarde 10\n"
  },
  {
    "id": "cb57551bb5c8519c548503fd",
    "title": "Alola Legends",
    "text": "Guardian Deities| Tapu lele\nUltra Beast | Naganadel\nCosmog Line | Lunala\nnecrozma | necrozma dawn\n"
  },
  {
    "id": "6f504969b07ab19c54855e49",
    "title": "Galar Legends",
    "text": "Legends of Galar | Zamazenta\nLegends of Galar crowned | Zamazenta crowned\nLegendary Bird Galar | articuno galar\nurshifu | urshifu single strike\nReins of Unity | spectrier\nReins of Unity Calyrex | calyrex shadow\n"
  },
  {
    "id": "261aa2fbbcca719c5485cca2",
    "title": "Paldea Legends",
    "text": "Treasures of Ruin | chi yu\nLegendary Beast Paradox | raging bolt\nSwords of Justice paradox | iron boulder\nThe Loyal Three | munkidori\nParadox Duo | Koraidon\n"
  }
];
